spring.application.name=authlab

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.expiration.time=900000
jwt.key=IQXFOP2sy3WLub5HXv&RM_nhvN3sc=1Y8rdz2F$_C$QtgGNBnij_RRhIMmSThf4yYCmSmhZ_qcIHDbKQesiK74tl70PrQMi6ThCR3$Hd=HzI6A-DCMJiJai2IJp32fXd_UxtEhG2kLO_8dbgzdm3htw2-13kJOLPfw#JxUw=9&VmwT5SxK!4W5Mc2&qhmYJYxiPok47G1KEt--10jPHsrZxMQJXRVUpuHIkky6mL7Auro-X1jvH8WEV1bhSfoxpSAE#pMraYUYE3v-tGT$rW-BcSRYP7Q0=Wu#a70xlUSVcKcLLvLXz$LU3qEJod0xwv=kCEmRBij1-iKufjCKfg_ehO